# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

def  depend_Pods
  pod ‘ZM_BaseLib’, :path=>'../ZM_BaseLib.podspec'

end


target 'ZM_BaseLibDemo’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  depend_Pods

end
