# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'ZM_DataBaseDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod ‘ZM_DataBase’, :path=>'../ZM_DataBase.podspec'
  # Pods for ZM_DataBaseDemo

end
