# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZM_NetworkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod ‘ZM_Networking’, :path=>’../ZM_Networking.podspec'
  # Pods for ZM_NetworkingDemo

end
